import type { MemberAbility } from './memberScenes'

export const memberChapters = {
  konan: {
    number: '05',
    name: 'KONAN.',
    secondName: 'THE PAPER ANGEL',
    epithet: 'A THOUSAND FOLDS OF RESOLVE',
    symbol: '\u767d',
    ring: 'WHITE',
    lead: 'Delicate as paper.',
    line: 'Unshakable as a promise.',
    story:
      'A founder, a friend, and the last keeper of a shared dream. Konan turned ordinary sheets into wings, letting every fold carry the resolve she rarely put into words.',
    ability: 'Dance of the Shikigami',
    action: 'Unfold the wings',
    active: 'SHIKIGAMI / A THOUSAND PAPER WINGS',
    idle: 'EVERY FOLD REMEMBERS',
    detail: 'Paper transformation',
    detailLabel: 'NINJUTSU',
    technique: 'Shikigami / Origami',
    next: '#kisame',
    nextName: 'The depth beneath the surface',
    eyebrow: 'SOME PROMISES NEVER LOSE THEIR SHAPE',
    japanese: '\u5f0f\u7d19',
  },
  kisame: {
    number: '06',
    name: 'KISAME.',
    secondName: 'HOSHIGAKI',
    epithet: 'THE TAILLESS TAILED BEAST',
    symbol: '\u5357',
    ring: 'SOUTH',
    lead: 'An ocean of chakra.',
    line: 'A loyalty deeper still.',
    story:
      'He had seen enough secrets to distrust the world. With the living blade Samehada at his side, Kisame found a rare kind of honesty in Itachi and a cause worth following to its depths.',
    ability: 'Water Prison',
    action: 'Raise the water prison',
    active: 'WATER PRISON / THE TIDE RISES',
    idle: 'THE DEEP DOES NOT FORGET',
    detail: 'Samehada',
    detailLabel: 'LIVING BLADE',
    technique: 'Water Release / Absorption',
    next: '#deidara',
    nextName: 'Beauty in a single instant',
    eyebrow: 'STILL WATER. LIMITLESS CHAKRA.',
    japanese: '\u9bab\u808c',
  },
  deidara: {
    number: '07',
    name: 'DEIDARA.',
    secondName: 'THE FLEETING ARTIST',
    epithet: 'A MASTERPIECE THAT WILL NOT LAST',
    symbol: '\u9752',
    ring: 'BLUE',
    lead: 'Make something beautiful.',
    line: 'Let the moment take it.',
    story:
      'A sculptor with no interest in permanence. Deidara shaped chakra-infused clay into soaring creations, finding the highest form of art in the instant before it disappeared.',
    ability: 'Explosive Clay',
    action: 'Release the clay',
    active: 'CLAY RELEASE / ONE UNREPEATABLE INSTANT',
    idle: 'NOT ALL ART IS MEANT TO STAY',
    detail: 'Chakra-infused clay',
    detailLabel: 'MEDIUM',
    technique: 'Sculpture / Release',
    next: '#sasori',
    nextName: 'Art that refuses to end',
    eyebrow: 'THE MOMENT IS THE MASTERPIECE',
    japanese: '\u82b8\u8853',
  },
  sasori: {
    number: '08',
    name: 'SASORI.',
    secondName: 'OF THE RED SAND',
    epithet: 'THE ARCHITECT OF ETERNITY',
    symbol: '\u7389',
    ring: 'JEWEL',
    lead: 'He made his art eternal.',
    line: 'Not his loneliness.',
    story:
      "Every joint, thread, and mechanism was a refusal to let time win. The Hidden Sand's master puppeteer built an enduring world of his own, but never quite replaced what he had lost.",
    ability: 'Red Secret Technique',
    action: 'Call the puppet theatre',
    active: 'RED SECRET / THE STRINGS AWAKEN',
    idle: 'TIME CANNOT TOUCH A PERFECT CREATION',
    detail: 'Chakra threads',
    detailLabel: 'CONTROL',
    technique: 'Puppet Technique',
    next: '#hidan',
    nextName: 'A devotion without an ending',
    eyebrow: 'EVERY MOVEMENT HAS A HIDDEN HAND',
    japanese: '\u8d64\u79d8\u6280',
  },
  hidan: {
    number: '09',
    name: 'HIDAN.',
    secondName: 'THE UNDYING',
    epithet: 'DEVOTION BEYOND MORTALITY',
    symbol: '\u4e09',
    ring: 'THREE',
    lead: 'No doubt. No restraint.',
    line: 'No final curtain.',
    story:
      "An unwavering follower of Jashin, Hidan carried his beliefs as openly as his triple-bladed scythe. His impossible endurance made him Kakuzu's most exasperating, and most enduring, partner.",
    ability: 'Jashin Sigil',
    action: 'Trace the sigil',
    active: 'JASHIN / THE SIGIL IS COMPLETE',
    idle: 'AN OATH WITHOUT AN END',
    detail: 'Triple-bladed scythe',
    detailLabel: 'SIGNATURE WEAPON',
    technique: 'Immortality / Ritual',
    next: '#kakuzu',
    nextName: 'Five natures. One survivor.',
    eyebrow: 'THE BELIEVER WHO NEVER DOUBTED',
    japanese: '\u4e0d\u6b7b',
  },
  kakuzu: {
    number: '10',
    name: 'KAKUZU.',
    secondName: 'THE COLLECTOR',
    epithet: 'A LIFETIME WAS ONLY THE BEGINNING',
    symbol: '\u5317',
    ring: 'NORTH',
    lead: 'Five chakra natures.',
    line: 'One relentless survivor.',
    story:
      'Older than the conflicts around him, Kakuzu approached the shinobi world as a balance sheet. Beneath his stitched exterior, Earth Grudge Fear connected a formidable collection of elemental powers.',
    ability: 'Earth Grudge Fear',
    action: 'Unbind the threads',
    active: 'EARTH GRUDGE FEAR / THE NATURES SEPARATE',
    idle: 'EVERY THREAD HOLDS SOMETHING BORROWED',
    detail: 'Five chakra natures',
    detailLabel: 'AFFINITIES',
    technique: 'Earth Grudge Fear',
    next: '#zetsu',
    nextName: 'The watcher beneath the roots',
    eyebrow: 'FIVE NATURES. COUNTLESS SECRETS.',
    japanese: '\u5730\u6028\u865e',
  },
  zetsu: {
    number: '11',
    name: 'ZETSU.',
    secondName: 'TWO SIDES. ONE SHADOW.',
    epithet: 'THE WORLD HAS AN UNSEEN WITNESS',
    symbol: '\u4ea5',
    ring: 'BOAR',
    lead: 'Half in the light.',
    line: 'Entirely out of sight.',
    story:
      "White and Black Zetsu shared a silhouette but not a purpose. Moving through the earth itself, they watched the Akatsuki's story unfold while quietly tending another, much older one.",
    ability: 'Mayfly',
    action: 'Merge with the earth',
    active: 'MAYFLY / NO TRACE REMAINS',
    idle: 'EVEN THE ROOTS HAVE EYES',
    detail: 'White / Black Zetsu',
    detailLabel: 'DUAL NATURE',
    technique: 'Mayfly / Infiltration',
    next: '#yahiko',
    nextName: 'Before the dream changed',
    eyebrow: 'THE QUIETEST PRESENCE KNOWS THE MOST',
    japanese: '\u7d76',
  },
  yahiko: {
    number: '12',
    name: 'YAHIKO.',
    secondName: 'THE FIRST DAWN',
    epithet: 'BEFORE FEAR, THERE WAS HOPE',
    symbol: '\u96e8',
    ring: 'FOUNDER',
    lead: 'Three friends in the rain.',
    line: 'One world worth changing.',
    story:
      "The first Akatsuki was built on Yahiko's belief that his homeland deserved peace. A student of Jiraiya and a user of Water Release, he gave Nagato and Konan a dream larger than survival.",
    ability: 'Water Release',
    action: 'Turn the tide',
    active: 'WATER RELEASE / A NEW CURRENT',
    idle: 'EVERY DAWN BEGINS WITH SOMEONE WHO BELIEVES',
    detail: 'Original Akatsuki',
    detailLabel: 'LEGACY',
    technique: 'Water Release / Leadership',
    next: '#members',
    nextName: 'The complete shadow archive',
    eyebrow: 'BEFORE THE RED CLOUDS',
    japanese: '\u5f25\u5f66',
  },
} satisfies Record<MemberAbility, Record<string, string>>

export const chapterOrder = [
  'pain',
  'tobi',
  'orochimaru',
  'konan',
  'kisame',
  'deidara',
  'sasori',
  'hidan',
  'kakuzu',
  'zetsu',
  'yahiko',
] as const

export const portraitSizes: Record<string, [number, number]> = {
  pain: [1376, 872],
  tobi: [1440, 1080],
  orochimaru: [1424, 1076],
  konan: [1440, 1080],
  kisame: [1440, 1076],
  deidara: [1440, 1080],
  sasori: [1460, 1197],
  hidan: [1440, 1080],
  kakuzu: [1440, 1080],
  zetsu: [1440, 1080],
  yahiko: [1440, 1076],
}
